version: '3'
services:
  webserver:
    container_name: '${PHPVERSION}'
    build: './bin/${PHPVERSION}'
    ports:
      - '${HOST_MACHINE_UNSECURE_HOST_PORT}:80'
      - '${HOST_MACHINE_SECURE_HOST_PORT}:443'
    volumes:
      - '${DOCUMENT_ROOT-./www}:/var/www/html'
      - '${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini'
      - '${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled'
      - '${LOG_DIR-./logs/apache2}:/var/log/apache2'
    environment:
      DB_HOST: mysqldb
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    build: './bin/${DATABASE}'
    ports:
      - 127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306
    volumes:
      - appdata:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ./bin/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    restart: always
  redis:
    container_name: redis
    image: redis:5-alpine
    ports:
      - 127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8888:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    restart: always
volumes:
  appdata:
    driver: local